<?php //Partial! ?>
<div class="webaceCommentList">
<?php $first=true; ?>
<?php foreach ($this->comments as $comment): ?>
  <?php if($first){$first=false;}else{echo "<hr/>";} ?>
  <div class="webacePageComment" id="webacePageComment<?php echo $comment['id']; ?>">
     <?php if($this->showUrl!=false): ?>
     <span class="webaceToPage" title="The page the comment was posted to">To: <a href="<?php echo $this->url(array('controller'=>'Index','action'=>'launch'),'default',true)."?url=".urlencode($comment['domain'].$comment['path']).'">.'.$comment['domain'].$comment['path'] ?></a></span>
     <?php endif; ?>
     <div class="webaceAvatar">
       <?php if(isset($comment['emailmd5'])): ?>
         <img class="webaceAvatarImg" src="http://www.gravatar.com/avatar/<?php echo $comment['emailmd5'] ?>" width="80" height="80" alt="Avatar" /><br/>
       <?php endif; ?>
       <span class="webaceNick"><a href="/Comment/user?mid=<?php echo $comment['id'] ?>"><?php echo $comment['nick'] ?></a></span><br/>
       <span class="webaceDate"><a href="/comment/show?id=<?php echo $comment['id'] ?>"><?php echo $comment['created'] ?></a></span>
     </div>
   <?php echo $this->escape($comment['content']) ?>
 </div>
<?php endforeach ?>
</div>
