<?php //Partial! ?>
<div class="webaceCommentList">
<?php foreach ($this->comments as $comment): ?>
  <div class="webacePageComment" id="webacePageComment<?php echo $comment['id']; ?>">
     <span class="webaceToPage" title="The page the comment was posted to">To: <a href="<?php echo $this->url(array('controller'=>'Index','action'=>'launch'),'default',true)."?url=".urlencode($comment['domain'].$comment['path']).'">.'.$comment['domain'].$comment['path'] ?></a></span>
     <div class="webaceAvatar">
       <?php if(isset($comment['emailmd5'])): ?>
         <img class="webaceAvatarImg" src="http://www.gravatar.com/avatar/<?php echo $comment['emailmd5'] ?>" width="80" height="80" alt="Avatar" /><br/>
       <?php endif; ?>
       <b><?php echo $comment['nick'] ?></b><br/>
       <span class="webaceDate"><?php echo $comment['created'] ?></span>
     </div>
   <?php echo $this->escape($comment['content']) ?>
   <hr/>
 </div>
<?php endforeach ?>
</div>
