<div id="view-content">
<h1>Recent Comments</h1>
<hr/>
  <?php foreach ($this->comments as $comment): ?>
    <dl>
      <dt>Date:</dt><dd><?php echo $this->escape($comment->created) ?></dd>
      <dt>Attached To:</dt><dd>http://<?php echo $this->escape($comment->domain.$comment->path) ?></dd>
      <dt>By:</dt><dd><?php echo $this->escape($comment->nick) ?> &lt;<?php echo $this->escape($comment->email) ?>&gt; (<?php echo $this->escape($comment->ip) ?>)</dd>
      <dt>Content:</dt><dd><?php echo $this->escape($comment->content) ?></dd>
    </dl>
    <hr/>
  <?php endforeach ?>
</div>
<br /><br />
