<h1>Add WebAce power to your website</h1>
<p>Anyone with our bookmarklet in their bookmarks/favourites
can view the WebAce tab on any website at any time.</p>
<p>However, Webmasters may also want to embed the WebAce
system into their website for <i>all</i> users, even those
who don't have the bookmarklet!</p>
<p>Copy the following code into any website's source
and it will make the webace tap appear, minimized,
at the bottom of that web page</p>
<code>
&lt;script type="text/javascript"&gt;
(function(){webaceStartMinimized=true; document.body.appendChild( document.createElement('script') ).src='http://webace.dalliance.net/static/webace.js';})()
&lt;/script&gt;
</code>

<p>We've added that code to this page, so you can
see what happens when you to: the webace tab
appears minimized on the page as soon as the
page has loaded.</p>

<script type="text/javascript"> (function(){webaceStartMinimized=true; document.body.appendChild( document.createElement('script') ).src='http://webace.dalliance.net/static/webace.js';})() </script> 
