<h1>Help</h1>
<p><b>WebAce</b> is a chat client which runs in your
browser. You can type messages, and anyone else
running <b>WebAce</b> from the same web-page will
be able to read and respond to your messages</p>
<p>This page tells you how to use it.</p>

<h1>Install</h1>
<p>To Install <b>WebAce</b>, drag the bookmarklet
into your favourites or bookmarks</p>
<p>Here's the bookmarklet:&nbsp;&nbsp;&nbsp;&nbsp; <a class="button" href="javascript:(function(){if(undefined===window.webacePaneHeight){document.body.appendChild(document.createElement('script')).src='http://webace.dalliance.net/static/webace.js';}else{alert('Already Running')}})();">Launch WebAce</a></p>

<h1>Launch</h1>
<p>When you are viewing a web page which you
would like to chat about, click the bookmark
you dragged into your browser in the above step.
This will launch the <b>WebAce</b> popup tab.</p>

<h1>Manipulate The Tab</h1>
<p>The <b>WebAce</b> tab can be minimized, 
maximized, or dragged up and down to whatever
size you want it to be. Click the handle to
min/maximize or drag it to move it.</p>


<h1>Read Messages</h1>
<p>When the tab opens, it'll display any
messages already posted to this page by other
users. It will automatically scroll to the
bottom, where the most recent messages are.</p>
<p>Each message is displayed with a little
card saying who wrote the message, showing
their avatar if they have one, and the time
the message was posted.</p>
<p>If there are <i>lots</i> of messages
then it'll just show the most recent few dozen 
with a link to load earlier messages if you scroll
all the way back to the top.</p>

<h1>Post messages</h1>
<p>To post a message to the chat, just type what
you want to say into the text-box at the bottom
of the tab and either press enter, or click the
"Send" button.</p>
<p>Your message will immediately be posted in
the chat!</p>

<h1>Read Replies</h1>
<p>If new messages come in while you have the
<b>WebAce</b> tab open, they will automatically
be displayed right away at the bottom of the
pane.</p>

<h1>Set Your Nickname</h1>
<p>When you first use <b>WebAce</b>, you can post
messages right away! However if you do so without
first setting a nickname, your message will
appear to come from "Anon_XXX". If you want to
use a nick-name on your messages, you need to
type the "Change nickname" command.</p>
<p>Type something like the following</p>
<code>/nick Jane Doe</code>
and press return. Of course replace "Jane
Doe" with whatever nickname you would like
to use.</p>
<p>You can change your nickname at any time,
but messages you have already posted will remain
tagged with the nickname you had when you posted
them. You can't change the nickname attached
to already-posted messages.</p>
<p>Nick-names are not exclusive, anyone
can post under any nickname they want. Everyone
can call themselves <i>Sparticus</i> or 
stay with their anonymous names. We don't
care.</p>

<h1>Set your email address</h1>
<p>How then do you keep any kind of persistent
identity? If you register your email address then
people will be able to view a list of all the 
posts you made under that email address.</p>
<p>To register your email address, just type
something similar to this:</p>
<code>/email jane.doe@test.com</code>
<p>And press return. Of course you will need to 
change the email address there to your own
email address.<p>
<p><b>WebAce</b> will then send an email to that
address. It will very likely end up in your spam
folder if you have one. The email will contain
a link which you must click to confirm that
your have supplied your own email address.</p>
<p>Users with confirmed email addresses
also get avatars, and can load and save their
session to preserve their identity!</p>

<h1>Set your avatar</h1>
<p><b>WebAce</b> uses the global avatar system
<a href="http://gravatar.com/">Gravatar</a>. At
Gravatar you can upload an avatar to associate
with your email address around the entire web!
Go to gravatar.com to see how to do this.</p>

<h1>View whole website's messages</h1>
<p>When you first launch <b>WebAce</b> you will
see only messages posted to the web page you
are visiting at the time you click the bookmarklet.
There may be very few people chatting about that
particular page, but <b>WebAce</b> has a mode
to allow you to view messages posted to any
page in the whole website, rather than just
that single page. Try it, type:</p>
<code>/mode domain</code>
<p>Messages will now be topped by a header
which tells you which page in the website
the messages was posted to. If you want
to reply, you will need to ensure your
message goes to the correct web-page. Do
this by clicking the little round radio-button
in the left of the header for the message
you want to reply to.</p>
<p>Now you should see many more messages,
every message for the whole internet site
rather than just that particular page.</p>

<h1>View all messages from everywhere!</h1>
<p>If you are <i>very</i> keen to chat, and
don't really care which pages you are chatting
<i>aboout</i>, you can instruct <b>WebAce</b> to
show you every comment to every page on the
entire internet.</p>
<p>This may be a <i>lot</i> of messages, so
be prepared for your <b>WebAce</b> tab to
scroll <i>very</i> quickly. Type the following:</p>
<code>/mode web</code>
</p>As with 'domain' mode, each post will now
have a header to say which web page it is
talking about. Click that header in a message
you wish to reply to.</p>

<h1>Reset to Single-Page mode</h1>
<p>If you want to get back to the original mode,
viewing only comments to the page you are
viewing <b>WebAce</b> from, type the following:</p>
<code>/mode page</code>
<p>The headers at the top of each new message
will no longer appear, since they are all messages
posted to the website you are currently visiting.</p>

<h1>Save your session settings</h1>
<p>If you've set up an email address and
don't want to have to re-confirm it next time,
don't want to have to change the mode to your
preferred system next time you use <b>WebAce</b>
and want to keep a consistent identity in the chat, 
you can save your session data.</p>
<p>You need to have confirmed your email as 
above, then type the following, replacing
PASSWORD with your password:</p>
<code>/save PASSWORD</code>
<p>Or, optionally, if you with to type it twice to confirm it:</p>
<code>/save PASSWORD PASSWORD</code>
<p>Passwords must not have spaces, but
can otherwise contain pretty much any
characters you want.</p>
<p>Data saved includes your nickname, your email,
the display mode which determines which
messages your <b>WebAce</b> displays, and
ensure the list of posts obtained by clicking
your user-name grows in the same page rather
than a new one.</p>

<h1>Load your sesssion settings</h1>
<p>If you have already saved a session, you can reload
it from the same computer at a different time, from
a different computer, from any web-page that 
<b>WebAce</b> connects to. Type this:</p>
<code>/load email@address.com PASSWORD</code>
<p>Obviously using the email address and password
you used when saving the session.</p>



