<h1>Help</h1>
<p><b>WebAce</b> is a chat client which runs in your
browser. You can type messages, and anyone else
running <b>WebAce</b> from the same web-page will
be able to read and respond to your messages</p>
<p>This page tells you how to use it.</p>

<h1>Install</h1>
<p>To Install <b>WebAce</b>, drag the bookmarklet
into your favourites or bookmarks</p>
<p>Here's the bookmarklet:&nbsp;&nbsp;&nbsp;&nbsp; <a class="button" href="javascript:(function(){if(undefined===window.webacePaneHeight){document.body.appendChild(document.createElement('script')).src='http://webace.dalliance.net/static/webace.js';}else{alert('Already Running')}})();">Launch WebAce</a></p>

<h1>Launch</h1>
<p>When you are viewing a web page which you
would like to chat about, click the bookmark
you dragged into your browser in the above step.
This will launch the <b>WebAce</b> popup tab.</p>

<h1>Manipulate The Tab</h1>
<p>The <b>WebAce</b> tab can be minimized, 
maximized, or dragged up and down to whatever
size you want it to be. Click the handle to
min/maximize or drag it to move it.</p>


<h1>Read Messages</h1>
<p>When the tab opens, it'll display any
messages already posted to this page by other
users. It will automatically scroll to the
bottom, where the most recent messages are.</p>
<p>Each message is displayed with a little
card saying who wrote the message, showing
their avatar if they have one, and the time
the message was posted.</p>
<p>If there are <i>lots</i> of messages
then it'll just show the most recent few dozen 
with a link to load earlier messages if you scroll
all the way back to the top.</p>

<h1>Post messages</h1>
<p>To post a message to the chat, just type what
you want to say into the text-box at the bottom
of the tab and either press enter, or click the
"Send" button.</p>
<p>Your message will immediately be posted in
the chat!</p>

<h1>Read Replies</h1>
<p>If new messages come in while you have the
<b>WebAce</b> tab open, they will automatically
be displayed right away at the bottom of the
pane.</p>

<h1>Set Your Nickname</h1>
<p>When you first use <b>WebAce</b>, you can post
messages right away! However if you do so without
first setting a nickname, your message will
appear to come from "Anon_XXX". If you want to
use a nick-name on your messages, you need to
type the "Change nickname" command.</p>
<p>Type something like the following</p>
<code>/nick Jane Doe</code>
and press return. Of course replace "Jane
Doe" with whatever nickname you would like
to use.</p>
<p>You can change your nickname at any time,
but messages you have already posted will remain
tagged with the nickname you had when you posted
them. You can't change the nickname attached
to already-posted messages.</p>
<p>Nick-names are not exclusive, anyone
can post under any nickname they want. Everyone
can call themselves <i>Sparticus</i> or 
stay with their anonymous names. We don't
care.</p>

<h1>Set your email address</h1>
<p>How then do you keep any kind of persistent
identity? If you register your email address then
people will be able to view a list of all the 
posts you made under that email address.</p>
<p>To register your email address, just type
something similar to this:</p>
<code>/email jane.doe@test.com</code>
<p>And press return. Of course you will need to 
change the email address there to your own
email address.<p>
<p><b>WebAce</b> will then send an email to that
address. It will very likely end up in your spam
folder if you have one. The email will contain
a link which you must click to confirm that
your have supplied your own email address.</p>
<p>Once you have clicked on the link, your
messages will appear with a link to a list
of your messages, and you will have an avatar!</p>

<h1>Set your avatar</h1>
<p><b>WebAce</b> uses the global avatar system
<a href="http://gravatar.com/">Gravatar</a>. At
Gravatar you can upload an avatar to associate
with your email address around the entire web!
Go to gravatar.com to see how to do this.</p>

<h1>Save your settings</h1>
<p>Planned feature not yet implemented.</p>
<code>/save PASSWORD CONFIRMPASSWORD</code>
<p>Or, optionally,</p>
<p>Planned feature not yet implemented.</p>
<code>/save PASSWORD CONFIRMPASSWORD</code>

<h1>Load your settings</h1>
<p>Planned feature not yet implemented.</p>
<code>/load email@address.com PASSWORD</code>

<h1>Advanced:<br/>View whole website's messages</h1>
<p>Planned feature not yet implemented.</p>
<code>/mode domain</code>

<h1>Advanced:<br/>View all messages from everywhere!</h1>
<p>Planned feature not yet implemented.</p>
<code>/mode web</code>

<h1>Advanced:<br/>Reset to Single-Page mode</h1>
<p>Planned feature not yet implemented.</p>
<code>/mode page</code>


<h1>Advanced:<br/>Auto-archive to email</h1>
<p>Planned feature not yet implemented.</p>
<code>/ccemail yes</code>

<h1>Advanced:<br/>Auto-post to tiwtter</h1>
<p>Planned feature not yet implemented.</p>

<h1>Advanced:<br/>Auto-post to facebook</h1>
<p>Planned feature not yet implemented.</p>

<h1>Advanced:<br/>Private Messages</h1>
<p>Planned feature not yet implemented.</p>

<h1>Advanced:<br/>Email Reply-Notification</h1>
<p>Planned feature not yet implemented.</p>



