<h1>Welcome</h1>
<p><b>First</b> there was A.C.E., Adam's Chat Engine built into phpbb
   as a chat-interface on the forum posts.</p>
<p><b>Now</b> there is <b>WebAce</b>, and Adam's Chat Engine is built into 
    <i>every page in the entire internet<b>!</b></i></p>
<h1>Instructions</h1>
<p>Simply drag the bookmarket below into your bookmarks toolbar,
   and then visit a web-page anywhere on the internet. If you
   want to chat about that page, click the bookmarklet in your
   toolbar.</p>
   Here's the bookmarklet:&nbsp;&nbsp;&nbsp;&nbsp; <a class="button" href="javascript:(function(){if(undefined===window.webacePaneHeight){document.body.appendChild(document.createElement('script')).src='http://webace.dalliance.net/static/webace.js';}else{alert('Already Running')}})();">Launch WebAce</a></li>

<h1>Try it now</h1>
<p>Clicking the bookmarklet will now will launch webAce on this
   welcome page, so you can test without installing!</p>
<h1>Hire Adam!</h1>
<p>I built this thing in order to learn how Zend works,
   since I'm looking for a job and most of the high waged
   web programming jobs seemed to mention Zend. Turns
   out Zend is pretty simple, pretty much a typical
   MVC, as expected.</p>
<p>If you want to hire me, I'm in London and my CV is
   <a href="http://dalliance.net/cv/">here</a>. Get in touch!</p>
