<html>
  <head>
    <title>webAce launching <?php echo $this->url; ?></title>
    <style type="text/css">
      html {overflow: auto;}
      html, body, iframe {margin: 0px; padding: 0px; height: 100%; border: none;}
      iframe {display: block; width: 100%; border: none; overflow-y: auto; overflow-x: hidden;}
</style> 
  </head>
  <body>
    <iframe id="webaceLaunchContent" src="about:blank" frameborder="0" marginheight="0" marginwidth="0" width="100%" height="100%" scrolling="auto"></iframe>
  </body>
</html>
<script type="text/javascript">
(function(){
   webaceServerDomainOverride='<?php echo $_SERVER['HTTP_HOST'];$_SERVER['SERVER_NAME']; ?>';webaceServerDomainOverride='<?php echo $_SERVER['HTTP_HOST'];$_SERVER['SERVER_NAME']; ?>';document.body.appendChild(document.createElement('script')).src='http://<?php echo $_SERVER['HTTP_HOST'];$_SERVER['SERVER_NAME']; ?>/static/webace.js';
   setTimeout(function(){
        $("#webaceLaunchContent").attr("src",'<?php echo $this->url; ?>');
   },1000);
})()
</script>
