<?php echo $this->doctype() ?>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>WebAce<?php if(isset($this->title)){echo " - ".$this->title;} ?></title>
  <?php echo $this->headLink()->appendStylesheet('/static/global.css') ?>
</head>
<body>
  <div id="page">
    <div id="header-logo">
        <h1>WebAce<h1>
        <h2>Adam's Chat Engine on <b>every</b> web page.</h2>
    </div>
    <div id="page-layout">
      <div id="header-navigation">
          <ul>
            <li> <a href="<?php echo $this->url( array('controller'=>''), 'default', true) ?>">Home</a></li>
            <li> <a href="<?php echo $this->url( array('controller'=>'Comment'), 'default', true) ?>">Latest Messages</a></li>
            <li> <a href="<?php echo $this->url( array('controller'=>'Comment', 'action'=>'hotconversations'), 'default', true) ?>">Hot Conversations</a></li>
            <li> <a href="<?php echo $this->url( array('controller'=>''), 'default', true) ?>?page=help">Help Page - Instructions</a></li>
            <li> <a href="<?php echo $this->url( array('controller'=>''), 'default', true) ?>?page=embed">Embed in your website</a></li>
            <li> <a href="javascript:(function(){if(undefined===window.webacePaneHeight){document.body.appendChild(document.createElement('script')).src='http://webace.dalliance.net/static/webace.js';}else{alert('Already Running')}})();">Launch WebAce</a></li>
            <li> <a href="<?php echo $this->url( array('controller'=>'Index','action'=>'logout'), 'default', true) ?>">Log Out</a></li>
          </ul>
      </div>
      <div id="content"> 
          <?php echo $this->layout()->content ?>
      </div> 
    </div> 
  </div>
  <div id="footer">
   <p>Powered By <a href="http://framework.zend.com/"><img src="/static/img/zend.png" /></a> <a href="http://jquery.com/"> <img src="/static/img/jquery.png" /></a> and <a href="http://dalliance.net/">Adam Priest</a></p>
  </div> 
</body>
</html>
