<?php echo $this->doctype() ?>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  <?php echo $this->headLink()->appendStylesheet('/static/global.css') ?>
</head>
<body>
  <div id="page">
    <div id="header-logo">
        <h1>WebAce - Chat in websites</h1>
    </div>
    <div id="header-navigation">
        <ul>
          <li> <a href="<?php echo $this->url( array('controller'=>'Index'), 'default', true) ?>">Home</a></li>
          <li> <a href="<?php echo $this->url( array('controller'=>'Comment'), 'default', true) ?>">Recent Comments</a></li>
          <li> <a href="<?php echo $this->url( array('controller'=>'Comment','action'=>'submit'), 'default', true) ?>">Submit Comment</a></li>
          <li> <a href="<?php echo $this->url( array('controller'=>'Index','action'=>'logout'), 'default', true) ?>">Log Out</a></li>
          <li> <a href="<?php echo $this->url( array('controller'=>'Index','action'=>'launch'), 'default', true) ?>?url=http://electronicwishingwell.com/">Launch At EWW</a></li>
          <li> <a href="javascript:(function(){if(undefined===window.webacePaneHeight){document.body.appendChild(document.createElement('script')).src='http://webace.dalliance.net/static/webace.js';}else{alert('Already Running')}})();">webAce - Start</a></li>
        </ul>
    </div>
    <div id="content"> 
        <?php echo $this->layout()->content ?>
    </div> 
  </div> 
</body>
</html>
